version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ci/build/main/Dockerfile
    env_file:
    - resources.ini
    environment:
      - WAIT_HOSTS=postgres:5432
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:15
    env_file: 
      - resources.ini
    ports:
      - "5444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data: