"""Init migration.

Revision ID: 0381723fc3bb
Revises:
Create Date: 2025-09-25 01:05:26.935701

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '0381723fc3bb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_invites',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('was_used', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('DEFAULT', 'ADMIN', 'SUPERADMIN', 'OWNER', name='user_role'), nullable=False),
    sa.Column('made_by_id', sa.BigInteger(), nullable=False),
    sa.Column('made_by_name', sa.String(length=256), nullable=False),
    sa.Column('used_by_id', sa.BigInteger(), nullable=True),
    sa.Column('used_by_name', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    )
    op.create_index('unq_active_invite_code', 'admin_invites', ['code'], unique=True, postgresql_where=False)
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'UNFINISHED', 'DELETED', name='upload_state'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_files_status'), 'files', ['status'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('role', sa.Enum('DEFAULT', 'ADMIN', 'SUPERADMIN', 'OWNER', name='user_role'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    )
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_state'), 'users', ['state'], unique=False)
    op.create_table('constant_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.BigInteger(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'UNFINISHED', 'DELETED', name='upload_state'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.user_id']),
    sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_constant_messages_status'), 'constant_messages', ['status'], unique=False)
    op.create_table('temporary_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.BigInteger(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'UNFINISHED', 'DELETED', name='upload_state'), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.user_id']),
    sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_temporary_messages_status'), 'temporary_messages', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_temporary_messages_status'), table_name='temporary_messages')
    op.drop_table('temporary_messages')
    op.drop_index(op.f('ix_constant_messages_status'), table_name='constant_messages')
    op.drop_table('constant_messages')
    op.drop_index(op.f('ix_users_state'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_files_status'), table_name='files')
    op.drop_table('files')
    op.drop_index('unq_active_invite_code', table_name='admin_invites', postgresql_where=False)
    op.drop_table('admin_invites')
    # ### end Alembic commands ###
